### ISSUE TITLE
ImplUtil class not found

### ISSUE THREAD

**Issue by 62mkv** [JetBrains/gradle-grammar-kit-plugin#23]
When the README says `NB: plugin does not support two-pass generation, therefore does not suport method mixins.` does this also mean that such constructions:

```
{  
  ...
  psiImplUtilClass="package.name.SomePsiImplUtil"
}

sql_statement ::= SQL_TOKEN  { methods=[isValidHost updateText createLiteralTextEscaper] implements="com.intellij.psi.PsiLanguageInjectionHost" }
```

are also not possible to use with a Gradle plugin? if yes, is it possible to provide more extensive explanation in the README? and are there plans/possibilities to support such functionality in the future?

**Comment by 62mkv** [comment]
PS: it feels as it's not possible with the plugin; keeps saying 'class not found'. And by the feel of it it's not clear how should it work, as the task is dependency for 'compileJava'.

**Comment by xuyuanxiang** [comment]
+1

**Comment by MTRNord** [comment]
This still happens for me too :/

**Comment by FingerArt** [comment]
+1

**Comment by gregsh** [comment]
@hurricup We can possibly solve multi-pass problem using Java Annotation Processor API.
No annotation is actually required. 

Pass the list of grammar files to an annotation processor via compiler args and then a universal annotation processor would run in several passes and do its work. We can use Lombok-like Java Compiler API hacks to modify the newly generated files in pass two, or find another way.

**Comment by JojOatXGME** [comment]
I'm wondering if Grammar-Kit could already get enough information from an [`ErrorType`](https://docs.oracle.com/en/java/javase/11/docs/api/java.compiler/javax/lang/model/type/ErrorType.html) if parameters or return types referring to classes generated by Grammar-Kit cannot be resolved yet. Then, no Lombok-like Java Compiler API hacks would be necessary. Anyway, I'm not sure which information can actually be obtained from an `ErrorType` since I have only limited experience with annotation processors. I guess a simple name would be enogth to match against types which would be generated by Grammar-Kit?

**Comment by JojOatXGME** [comment]
I implemented a PoC for an annotation processor at [JojOatXGME/Grammar-Kit-Annotation-Processor]. As noted in my last comment, it seems to work without *Lombok-like Java Compiler API hacks*. I have only tested it with OpenJDK. It is still a bit hacky (see [here](https://github.com/JojOatXGME/Grammar-Kit-Annotation-Processor/blob/4468378d6b8c6fcc60a2ef21714e55567a1a85ec/src/main/java/dev/johanness/grammarkit/processor/GrammarKitProcessor.java#L126-L143) for example), mostly because Grammar-Kit does not have a proper tooling API which allows for dependency injection. In some cases, the generated files might also miss imports or use incorrect types, but it should be possible to fix if Grammar-Kit would provide the names of all classes it is about to generate before it generates them.

[JojOatXGME/Grammar-Kit-Annotation-Processor]:
<https://github.com/JojOatXGME/Grammar-Kit-Annotation-Processor>
"JojOatXGME/Grammar-Kit-Annotation-Processor: Proof of concept for running Grammar-Kit as an annotation processor."

**Comment by gregsh** [comment]
@JojOatXGME That is awesome. I've never had time to look into the annotation processor API myself.
I'd like to add the annotation processor to Grammar-Kit based on your work. Would you like to submit a PR?

Regarding the "Limitations" section:
1. Running JFlex on a specific *.flex file can be automated in Gradle, no need to address that.
2. "If the class behind psiImplUtilClass..." 
     That needs to be solved. The goal is to have exactly the same output as in the manual invocation.
3. Solvable for sure. 
4. I hope that one is solvable too. What needs to be done?

**Comment by JojOatXGME** [comment]
I can create a pull request, but it may take a few weeks because I'm a bit busy. 😄 Did I understand you correctly that the pull request shall target the [Grammar-Kit repository](https://github.com/JetBrains/Grammar-Kit) directly?

Besides that, I think it might be good to test the annotation processor with a few more compilers. (Are there still important Java compilers apart from OpenJDK?) I have not that much experience with annotation processors and the documentations is sometimes a little fuzzy. So I could imagine that some compilers behave a bit differently and introduce new problems.

> 4\. I hope that one is solvable too. What needs to be done?

We would need to capture diagnostic output (e.g. from `ParserGeneratorUtil.addWarning`), so we can forward it to [`Messager.printMessage`](https://docs.oracle.com/en/java/javase/15/docs/api/java.compiler/javax/annotation/processing/Messager.html#printMessage(javax.tools.Diagnostic.Kind,java.lang.CharSequence)).

**Comment by gregsh** [comment]
@JojOatXGME 

> I can create a pull request, but it may take a few weeks because I'm a bit busy. 😄 Did I understand you correctly that the pull request shall target the Grammar-Kit repository directly?

Yes, PR for GK repository. I can do it myself and reference you any way you like.

>> 4. I hope that one is solvable too. What needs to be done?

>We would need to capture diagnostic output (e.g. from ParserGeneratorUtil.addWarning), so we can forward it to Messager.printMessage.

Got it. Looks trivial.


> 2. "If the class behind psiImplUtilClass..."

What needs to be done here?

**Comment by JojOatXGME** [comment]
> Yes, PR for GK repository. I can do it myself and reference you any way you like.

I would like to prepare a pull request if you have time to wait for one or two weeks. If you want to work on it right away, you may do it yourself.

> > 1. "If the class behind psiImplUtilClass..."
> 
> What needs to be done here?

Well, that is more complicated. The `JavaHelper` implementation resolves the parameter types of methods in the `psiImplUtilClass`. Some of these types cannot be resolved by the compiler because Grammar-Kit is just about to create the related classes. In such cases, the annotation processor makes some custom resolution ([see sources](https://github.com/JojOatXGME/Grammar-Kit-Annotation-Processor/blob/4468378d6b8c6fcc60a2ef21714e55567a1a85ec/src/main/java/dev/johanness/grammarkit/processor/MyJavaHelper.java#L304-L328)). This currently breaks in certain situations. We would need to update this code to reliably resolve the types against the list of classes Grammar-Kit is about to create. If the type is not part of the list, we should probably abort the generation and try it again on the [next round](https://docs.oracle.com/en/java/javase/15/docs/api/java.compiler/javax/annotation/processing/Processor.html#process(java.util.Set,javax.annotation.processing.RoundEnvironment)). Hope that was somewhat understandable.

**Comment by gregsh** [comment]
@JojOatXGME I've done some preparations and played with the processor in the "in-ide" (not gradle) mode with [Perl5-IDEA](https://github.com/Camelcade/Perl5-IDEA) plugin. And I've stumbled upon a critical problem that looks like [JDK-8159770](https://bugs.openjdk.java.net/browse/JDK-8159770). The annotation processor is simply not invoked because `PerlFormattingTokenSets` extends `PerlElementTypes` which is not yet available. It is a number 409 error out of a total of 907 at that point. And for some reason, it is declared as non-recoverable. So `JavaCompiler#processAnnotations` exits without doing anything (`shouldStop(CompileState.PROCESS)==true`).

**Comment by JojOatXGME** [comment]
@gregsh That is a problem and I do not have a solution for it. However, there seems to be more to the story than just `A extends Generated_B`. I was not able to reproduce the issue within [this minimal example](https://github.com/JojOatXGME/Grammar-Kit-Annotation-Processor/blob/fd86ad6fbc2165a4d45489666bdc5f2666f8b17c/example/src/main/java/myexample/A.java). Maybe you can check if it works with your JDK as well.

Another topic: After some more research about the different packages, I want to mention that I am actually using non-standard APIs (i.e. `jdk.compiler`). I use them to get information about imports. This means the processor does probably not work on other compilers like `ecj` (Eclipse).

**Comment by gregsh** [comment]
@JojOatXGME A non-resolvable import statement produces a non-recoverable error. Can you try that?

**Comment by JojOatXGME** [comment]
@gregsh If you send me the patch, I can take a look at it. If it is not too complicated, maybe you can also describe how to reproduce the issue?

Regarding non-resolvable imports: I moved the generated class of my attempt to reproduce the issue into another package and inserted an import [[ref](https://github.com/JojOatXGME/Grammar-Kit-Annotation-Processor/commit/b10ce72bbab697e9eb55444e05b3fa5f5074e39f)], but it is still working. If I insert `class Defective extends String {}` (unrecoverable error according to JDK-8159770), the annotation processor is not executed.

**Comment by JojOatXGME** [comment]
@gregsh Looks like a bug (?) of Javac to me. A static or non-static import of a nonexistent class is recoverable. But if you have a static import of a nonexistent member of an existent class, Javac treats it as nonrecoverable.

```java
import static pkg.ExistentClass.CONSTANT;
```

```
public class ExistentClass extends NonExistendClass {
}
```

In this example, Javac treats the import as nonrecoverable because it cannot find `CONSTANT` in `ExistentClass`. Since annotation processors cannot modify classes, I guess Javac assumes the error is unrecoverable. However, since `ExistentClass` extends `NonExistendClass`, an annotation processor could actually generate that constant, which means the error should be recoverable.

**Comment by gregsh** [comment]
@JojOatXGME I've managed to get JavaC GrammarPlugin working with IntelliJ build system and with Gradle.
Here's the branch https://github.com/JetBrains/Grammar-Kit/commits/javac-plugin.

The required Gradle configuration is commented in `build.gradle`. One can try it out right away. I guess `gradle-grammar-kit-plugin` would make those configs much easier in the future.

Currently, array type annotations are a bit off (`@NotNull A[]` instead of `A @NotNull []`).
Another thing that occurred to me was that it did not work with plugins in Kotlin.

**Comment by JojOatXGME** [comment]
@gregsh I have looked at your commits and left a few comments.

Regarding the switch to a compiler plugin: Since we were already using APIs of the compiler API (module `jdk.compiler`), I guess we might as well create a compiler plugin instead of an annotation processor.

I think the biggest takeaway is that it seems impossible to create an annotation processor for Grammar-Kit without non-standard APIs. This means the approach is not compiler independent and does currently not support other compilers (like *ecj* or *Kotlin*). I have no idea how difficult it would be to create a similar plugin for Kotlin.

**Comment by gregsh** [comment]
@JojOatXGME 
> I did try to run your plugin by uncommenting the configuration of you last commit, but I got the following exception.

Fixed that in `'com.github.JetBrains:Grammar-Kit:cd365b7'`
